# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\bmahabir\Desktop\EDS_DATA_GUI\front_end.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(379, 394)
        Dialog.setAcceptDrops(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("c:\\Users\\bmahabir\\Desktop\\EDS_DATA_GUI\\../Sol-Clarity-Logo-300x127.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.openFile = QtWidgets.QPushButton(Dialog)
        self.openFile.setGeometry(QtCore.QRect(70, 100, 75, 23))
        self.openFile.setObjectName("openFile")
        self.CSV_label = QtWidgets.QLabel(Dialog)
        self.CSV_label.setGeometry(QtCore.QRect(180, 100, 111, 31))
        self.CSV_label.setObjectName("CSV_label")
        self.SR = QtWidgets.QPushButton(Dialog)
        self.SR.setGeometry(QtCore.QRect(20, 160, 75, 23))
        self.SR.setObjectName("SR")
        self.OPR = QtWidgets.QPushButton(Dialog)
        self.OPR.setGeometry(QtCore.QRect(110, 160, 75, 23))
        self.OPR.setObjectName("OPR")
        self.P_Eff = QtWidgets.QPushButton(Dialog)
        self.P_Eff.setGeometry(QtCore.QRect(200, 160, 101, 23))
        self.P_Eff.setObjectName("P_Eff")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 511, 91))
        self.label_2.setObjectName("label_2")
        self.Eff_Label = QtWidgets.QLabel(Dialog)
        self.Eff_Label.setGeometry(QtCore.QRect(10, 130, 141, 21))
        self.Eff_Label.setObjectName("Eff_Label")
        self.Graph_label = QtWidgets.QLabel(Dialog)
        self.Graph_label.setGeometry(QtCore.QRect(10, 210, 131, 21))
        self.Graph_label.setObjectName("Graph_label")
        self.Panel_sel = QtWidgets.QComboBox(Dialog)
        self.Panel_sel.setGeometry(QtCore.QRect(10, 280, 69, 22))
        self.Panel_sel.setObjectName("Panel_sel")
        self.Panel_sel.addItem("")
        self.Panel_sel.addItem("")
        self.Panel_sel.addItem("")
        self.Panel_sel.addItem("")
        self.Panel_sel.addItem("")
        self.Panel_sel.addItem("")
        self.Panel_sel.addItem("")
        self.gdata_sel = QtWidgets.QComboBox(Dialog)
        self.gdata_sel.setGeometry(QtCore.QRect(110, 280, 69, 22))
        self.gdata_sel.setObjectName("gdata_sel")
        self.gdata_sel.addItem("")
        self.gdata_sel.addItem("")
        self.gdata_sel.addItem("")
        self.gdata_sel.addItem("")
        self.gdata_sel.addItem("")
        self.gdata_sel.addItem("")
        self.graph = QtWidgets.QPushButton(Dialog)
        self.graph.setGeometry(QtCore.QRect(40, 320, 75, 23))
        self.graph.setObjectName("graph")
        self.graph_instruct = QtWidgets.QLabel(Dialog)
        self.graph_instruct.setGeometry(QtCore.QRect(10, 240, 211, 16))
        self.graph_instruct.setObjectName("graph_instruct")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "EDS Data Analysis Software"))
        self.openFile.setText(_translate("Dialog", "Find CSV File"))
        self.CSV_label.setText(_translate("Dialog", "<html><head/><body><p><br/>placeholder</p></body></html>"))
        self.SR.setText(_translate("Dialog", "Soiling Rates"))
        self.OPR.setText(_translate("Dialog", "OPR"))
        self.P_Eff.setText(_translate("Dialog", "Panel Efficiency"))
        self.label_2.setText(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; font-weight:600;\">Load Data</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; color:#000000;\">Push the &quot;Find CSV&quot; button and a pop up will appear. </span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; color:#000000;\">Click on the csv file named &quot;eds_data.csv&quot; to load the csv file. </span><br /></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.Eff_Label.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Efficieny calculators</span></p></body></html>"))
        self.Graph_label.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Graph Vizualization</span></p></body></html>"))
        self.Panel_sel.setItemText(0, _translate("Dialog", "EDS PV 1"))
        self.Panel_sel.setItemText(1, _translate("Dialog", "EDS PV 2"))
        self.Panel_sel.setItemText(2, _translate("Dialog", "EDS PV 3"))
        self.Panel_sel.setItemText(3, _translate("Dialog", "EDS PV 4"))
        self.Panel_sel.setItemText(4, _translate("Dialog", "EDS PV 5"))
        self.Panel_sel.setItemText(5, _translate("Dialog", "CTRL 1"))
        self.Panel_sel.setItemText(6, _translate("Dialog", "CTRL 2"))
        self.gdata_sel.setItemText(0, _translate("Dialog", "VOC"))
        self.gdata_sel.setItemText(1, _translate("Dialog", "ISC"))
        self.gdata_sel.setItemText(2, _translate("Dialog", "SI"))
        self.gdata_sel.setItemText(3, _translate("Dialog", "PR"))
        self.gdata_sel.setItemText(4, _translate("Dialog", "POUT"))
        self.gdata_sel.setItemText(5, _translate("Dialog", "GPOA"))
        self.graph.setText(_translate("Dialog", "Graph"))
        self.graph_instruct.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:10pt;\">Choose parameters and click graph</span></p></body></html>"))
